In [28]:
import pandas as pd

def cuadrado_medio(semilla, n):
    # Variables iniciales
    resultado = []
    k = len(str(semilla))
    r = semilla

    for i in range(n+1):
        rn_cuadrado = r ** 2
        mrn_cuadrado = int(str(rn_cuadrado)[1:-1])
        val1 = int(str(mrn_cuadrado)[:k])
        val2 = int(str(mrn_cuadrado)[-k:])

        resultado.append([ r, rn_cuadrado, mrn_cuadrado, val1, val2])

        if val1 == 0:
            break

        r = val1

    # Crear un DataFrame
    df = pd.DataFrame(resultado, columns=[ "R(n)", "R(n)^2", "MR(n)^2", "Val 1", "Val 2"])

    return df

semilla = 985
n = 30

df = cuadrado_medio(semilla, n)
df

    R(n)  R(n)^2  MR(n)^2  Val 1  Val 2
0    985  970225     7022    702     22
1    702  492804     9280    928    280
2    928  861184     6118    611    118
3    611  373321     7332    733    332
4    733  537289     3728    372    728
5    372  138384     3838    383    838
6    383  146689     4668    466    668
7    466  217156     1715    171    715
8    171   29241      924    924    924
9    924  853776     5377    537    377
10   537  288369     8836    883    836
11   883  779689     7968    796    968
12   796  633616     3361    336    361
13   336  112896     1289    128    289
14   128   16384      638    638    638
15   638  407044      704    704    704
16   704  495616     9561    956    561
17   956  913936     1393    139    393
18   139   19321      932    932    932
19   932  868624     6862    686    862
20   686  470596     7059    705     59
21   705  497025     9702    970    702
22   970  940900     4090    409     90
23   409  167281     6728    672    728
24   672  451584     5158    515    158
25   515  265225     6522    652    522
26   652  425104     2510    251    510
27   251   63001      300    300    300
28   300   90000        0      0      0